services:
  pg_test:
    image: pgvector/pgvector:pg17
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker
