/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceCreateRouteImport } from './routes/workspace/create'
import { Route as WorkspaceSlugRouteRouteImport } from './routes/workspace/$slug/route'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace/$slug/index'
import { Route as WorkspaceSlugTeamsIndexRouteImport } from './routes/workspace/$slug/teams/index'
import { Route as WorkspaceSlugTeamsTeamSlugIssuesCreateRouteImport } from './routes/workspace/$slug/teams/$teamSlug/issues/create'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCreateRoute = WorkspaceCreateRouteImport.update({
  id: '/workspace/create',
  path: '/workspace/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRouteRoute = WorkspaceSlugRouteRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)
const WorkspaceSlugTeamsIndexRoute = WorkspaceSlugTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)
const WorkspaceSlugTeamsTeamSlugIssuesCreateRoute =
  WorkspaceSlugTeamsTeamSlugIssuesCreateRouteImport.update({
    id: '/teams/$teamSlug/issues/create',
    path: '/teams/$teamSlug/issues/create',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteRouteWithChildren
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/teams': typeof WorkspaceSlugTeamsIndexRoute
  '/workspace/$slug/teams/$teamSlug/issues/create': typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/teams': typeof WorkspaceSlugTeamsIndexRoute
  '/workspace/$slug/teams/$teamSlug/issues/create': typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteRouteWithChildren
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/teams/': typeof WorkspaceSlugTeamsIndexRoute
  '/workspace/$slug/teams/$teamSlug/issues/create': typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/workspace/$slug'
    | '/workspace/create'
    | '/workspace/$slug/'
    | '/workspace/$slug/teams'
    | '/workspace/$slug/teams/$teamSlug/issues/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/workspace/create'
    | '/workspace/$slug'
    | '/workspace/$slug/teams'
    | '/workspace/$slug/teams/$teamSlug/issues/create'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/workspace/$slug'
    | '/workspace/create'
    | '/workspace/$slug/'
    | '/workspace/$slug/teams/'
    | '/workspace/$slug/teams/$teamSlug/issues/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  WorkspaceSlugRouteRoute: typeof WorkspaceSlugRouteRouteWithChildren
  WorkspaceCreateRoute: typeof WorkspaceCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/create': {
      id: '/workspace/create'
      path: '/workspace/create'
      fullPath: '/workspace/create'
      preLoaderRoute: typeof WorkspaceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/teams/': {
      id: '/workspace/$slug/teams/'
      path: '/teams'
      fullPath: '/workspace/$slug/teams'
      preLoaderRoute: typeof WorkspaceSlugTeamsIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/teams/$teamSlug/issues/create': {
      id: '/workspace/$slug/teams/$teamSlug/issues/create'
      path: '/teams/$teamSlug/issues/create'
      fullPath: '/workspace/$slug/teams/$teamSlug/issues/create'
      preLoaderRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
  }
}

interface WorkspaceSlugRouteRouteChildren {
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugTeamsIndexRoute: typeof WorkspaceSlugTeamsIndexRoute
  WorkspaceSlugTeamsTeamSlugIssuesCreateRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
}

const WorkspaceSlugRouteRouteChildren: WorkspaceSlugRouteRouteChildren = {
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugTeamsIndexRoute: WorkspaceSlugTeamsIndexRoute,
  WorkspaceSlugTeamsTeamSlugIssuesCreateRoute:
    WorkspaceSlugTeamsTeamSlugIssuesCreateRoute,
}

const WorkspaceSlugRouteRouteWithChildren =
  WorkspaceSlugRouteRoute._addFileChildren(WorkspaceSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  WorkspaceSlugRouteRoute: WorkspaceSlugRouteRouteWithChildren,
  WorkspaceCreateRoute: WorkspaceCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
