/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceCreateRouteImport } from './routes/workspace/create'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as WorkspaceSlugRouteRouteImport } from './routes/workspace/$slug/route'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/workspace/$slug/index'
import { Route as WorkspaceSlugTeamsIndexRouteImport } from './routes/workspace/$slug/teams/index'
import { Route as WorkspaceSlugSettingsRolesIndexRouteImport } from './routes/workspace/$slug/settings/roles/index'
import { Route as WorkspaceSlugSettingsMembersIndexRouteImport } from './routes/workspace/$slug/settings/members/index'
import { Route as WorkspaceSlugSettingsLabelsIndexRouteImport } from './routes/workspace/$slug/settings/labels/index'
import { Route as WorkspaceSlugTeamsTeamSlugIssuesRouteRouteImport } from './routes/workspace/$slug/teams/$teamSlug/issues/route'
import { Route as WorkspaceSlugTeamsTeamSlugIssuesSearchTestRouteImport } from './routes/workspace/$slug/teams/$teamSlug/issues/search-test'
import { Route as WorkspaceSlugTeamsTeamSlugIssuesCreateRouteImport } from './routes/workspace/$slug/teams/$teamSlug/issues/create'
import { Route as WorkspaceSlugTeamsTeamSlugIssueIssueIdRouteImport } from './routes/workspace/$slug/teams/$teamSlug/issue/$issueId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCreateRoute = WorkspaceCreateRouteImport.update({
  id: '/workspace/create',
  path: '/workspace/create',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRouteRoute = WorkspaceSlugRouteRouteImport.update({
  id: '/workspace/$slug',
  path: '/workspace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)
const WorkspaceSlugTeamsIndexRoute = WorkspaceSlugTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => WorkspaceSlugRouteRoute,
} as any)
const WorkspaceSlugSettingsRolesIndexRoute =
  WorkspaceSlugSettingsRolesIndexRouteImport.update({
    id: '/settings/roles/',
    path: '/settings/roles/',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)
const WorkspaceSlugSettingsMembersIndexRoute =
  WorkspaceSlugSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)
const WorkspaceSlugSettingsLabelsIndexRoute =
  WorkspaceSlugSettingsLabelsIndexRouteImport.update({
    id: '/settings/labels/',
    path: '/settings/labels/',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)
const WorkspaceSlugTeamsTeamSlugIssuesRouteRoute =
  WorkspaceSlugTeamsTeamSlugIssuesRouteRouteImport.update({
    id: '/teams/$teamSlug/issues',
    path: '/teams/$teamSlug/issues',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)
const WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute =
  WorkspaceSlugTeamsTeamSlugIssuesSearchTestRouteImport.update({
    id: '/search-test',
    path: '/search-test',
    getParentRoute: () => WorkspaceSlugTeamsTeamSlugIssuesRouteRoute,
  } as any)
const WorkspaceSlugTeamsTeamSlugIssuesCreateRoute =
  WorkspaceSlugTeamsTeamSlugIssuesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => WorkspaceSlugTeamsTeamSlugIssuesRouteRoute,
  } as any)
const WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute =
  WorkspaceSlugTeamsTeamSlugIssueIssueIdRouteImport.update({
    id: '/teams/$teamSlug/issue/$issueId',
    path: '/teams/$teamSlug/issue/$issueId',
    getParentRoute: () => WorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/teams/': typeof WorkspaceSlugTeamsIndexRoute
  '/workspace/$slug/teams/$teamSlug/issues': typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRouteWithChildren
  '/workspace/$slug/settings/labels/': typeof WorkspaceSlugSettingsLabelsIndexRoute
  '/workspace/$slug/settings/members/': typeof WorkspaceSlugSettingsMembersIndexRoute
  '/workspace/$slug/settings/roles/': typeof WorkspaceSlugSettingsRolesIndexRoute
  '/workspace/$slug/teams/$teamSlug/issue/$issueId': typeof WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute
  '/workspace/$slug/teams/$teamSlug/issues/create': typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
  '/workspace/$slug/teams/$teamSlug/issues/search-test': typeof WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/$slug': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/teams': typeof WorkspaceSlugTeamsIndexRoute
  '/workspace/$slug/teams/$teamSlug/issues': typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRouteWithChildren
  '/workspace/$slug/settings/labels': typeof WorkspaceSlugSettingsLabelsIndexRoute
  '/workspace/$slug/settings/members': typeof WorkspaceSlugSettingsMembersIndexRoute
  '/workspace/$slug/settings/roles': typeof WorkspaceSlugSettingsRolesIndexRoute
  '/workspace/$slug/teams/$teamSlug/issue/$issueId': typeof WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute
  '/workspace/$slug/teams/$teamSlug/issues/create': typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
  '/workspace/$slug/teams/$teamSlug/issues/search-test': typeof WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workspace/$slug': typeof WorkspaceSlugRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/invite/$token': typeof InviteTokenRoute
  '/workspace/create': typeof WorkspaceCreateRoute
  '/workspace/$slug/': typeof WorkspaceSlugIndexRoute
  '/workspace/$slug/teams/': typeof WorkspaceSlugTeamsIndexRoute
  '/workspace/$slug/teams/$teamSlug/issues': typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRouteWithChildren
  '/workspace/$slug/settings/labels/': typeof WorkspaceSlugSettingsLabelsIndexRoute
  '/workspace/$slug/settings/members/': typeof WorkspaceSlugSettingsMembersIndexRoute
  '/workspace/$slug/settings/roles/': typeof WorkspaceSlugSettingsRolesIndexRoute
  '/workspace/$slug/teams/$teamSlug/issue/$issueId': typeof WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute
  '/workspace/$slug/teams/$teamSlug/issues/create': typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
  '/workspace/$slug/teams/$teamSlug/issues/search-test': typeof WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/workspace/$slug'
    | '/api/$'
    | '/invite/$token'
    | '/workspace/create'
    | '/workspace/$slug/'
    | '/workspace/$slug/teams/'
    | '/workspace/$slug/teams/$teamSlug/issues'
    | '/workspace/$slug/settings/labels/'
    | '/workspace/$slug/settings/members/'
    | '/workspace/$slug/settings/roles/'
    | '/workspace/$slug/teams/$teamSlug/issue/$issueId'
    | '/workspace/$slug/teams/$teamSlug/issues/create'
    | '/workspace/$slug/teams/$teamSlug/issues/search-test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/$'
    | '/invite/$token'
    | '/workspace/create'
    | '/workspace/$slug'
    | '/workspace/$slug/teams'
    | '/workspace/$slug/teams/$teamSlug/issues'
    | '/workspace/$slug/settings/labels'
    | '/workspace/$slug/settings/members'
    | '/workspace/$slug/settings/roles'
    | '/workspace/$slug/teams/$teamSlug/issue/$issueId'
    | '/workspace/$slug/teams/$teamSlug/issues/create'
    | '/workspace/$slug/teams/$teamSlug/issues/search-test'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/workspace/$slug'
    | '/api/$'
    | '/invite/$token'
    | '/workspace/create'
    | '/workspace/$slug/'
    | '/workspace/$slug/teams/'
    | '/workspace/$slug/teams/$teamSlug/issues'
    | '/workspace/$slug/settings/labels/'
    | '/workspace/$slug/settings/members/'
    | '/workspace/$slug/settings/roles/'
    | '/workspace/$slug/teams/$teamSlug/issue/$issueId'
    | '/workspace/$slug/teams/$teamSlug/issues/create'
    | '/workspace/$slug/teams/$teamSlug/issues/search-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  WorkspaceSlugRouteRoute: typeof WorkspaceSlugRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  InviteTokenRoute: typeof InviteTokenRoute
  WorkspaceCreateRoute: typeof WorkspaceCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/create': {
      id: '/workspace/create'
      path: '/workspace/create'
      fullPath: '/workspace/create'
      preLoaderRoute: typeof WorkspaceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug': {
      id: '/workspace/$slug'
      path: '/workspace/$slug'
      fullPath: '/workspace/$slug'
      preLoaderRoute: typeof WorkspaceSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$slug/': {
      id: '/workspace/$slug/'
      path: '/'
      fullPath: '/workspace/$slug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/teams/': {
      id: '/workspace/$slug/teams/'
      path: '/teams'
      fullPath: '/workspace/$slug/teams/'
      preLoaderRoute: typeof WorkspaceSlugTeamsIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/settings/roles/': {
      id: '/workspace/$slug/settings/roles/'
      path: '/settings/roles'
      fullPath: '/workspace/$slug/settings/roles/'
      preLoaderRoute: typeof WorkspaceSlugSettingsRolesIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/settings/members/': {
      id: '/workspace/$slug/settings/members/'
      path: '/settings/members'
      fullPath: '/workspace/$slug/settings/members/'
      preLoaderRoute: typeof WorkspaceSlugSettingsMembersIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/settings/labels/': {
      id: '/workspace/$slug/settings/labels/'
      path: '/settings/labels'
      fullPath: '/workspace/$slug/settings/labels/'
      preLoaderRoute: typeof WorkspaceSlugSettingsLabelsIndexRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/teams/$teamSlug/issues': {
      id: '/workspace/$slug/teams/$teamSlug/issues'
      path: '/teams/$teamSlug/issues'
      fullPath: '/workspace/$slug/teams/$teamSlug/issues'
      preLoaderRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
    '/workspace/$slug/teams/$teamSlug/issues/search-test': {
      id: '/workspace/$slug/teams/$teamSlug/issues/search-test'
      path: '/search-test'
      fullPath: '/workspace/$slug/teams/$teamSlug/issues/search-test'
      preLoaderRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesSearchTestRouteImport
      parentRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRoute
    }
    '/workspace/$slug/teams/$teamSlug/issues/create': {
      id: '/workspace/$slug/teams/$teamSlug/issues/create'
      path: '/create'
      fullPath: '/workspace/$slug/teams/$teamSlug/issues/create'
      preLoaderRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRouteImport
      parentRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRoute
    }
    '/workspace/$slug/teams/$teamSlug/issue/$issueId': {
      id: '/workspace/$slug/teams/$teamSlug/issue/$issueId'
      path: '/teams/$teamSlug/issue/$issueId'
      fullPath: '/workspace/$slug/teams/$teamSlug/issue/$issueId'
      preLoaderRoute: typeof WorkspaceSlugTeamsTeamSlugIssueIssueIdRouteImport
      parentRoute: typeof WorkspaceSlugRouteRoute
    }
  }
}

interface WorkspaceSlugTeamsTeamSlugIssuesRouteRouteChildren {
  WorkspaceSlugTeamsTeamSlugIssuesCreateRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesCreateRoute
  WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute
}

const WorkspaceSlugTeamsTeamSlugIssuesRouteRouteChildren: WorkspaceSlugTeamsTeamSlugIssuesRouteRouteChildren =
  {
    WorkspaceSlugTeamsTeamSlugIssuesCreateRoute:
      WorkspaceSlugTeamsTeamSlugIssuesCreateRoute,
    WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute:
      WorkspaceSlugTeamsTeamSlugIssuesSearchTestRoute,
  }

const WorkspaceSlugTeamsTeamSlugIssuesRouteRouteWithChildren =
  WorkspaceSlugTeamsTeamSlugIssuesRouteRoute._addFileChildren(
    WorkspaceSlugTeamsTeamSlugIssuesRouteRouteChildren,
  )

interface WorkspaceSlugRouteRouteChildren {
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugTeamsIndexRoute: typeof WorkspaceSlugTeamsIndexRoute
  WorkspaceSlugTeamsTeamSlugIssuesRouteRoute: typeof WorkspaceSlugTeamsTeamSlugIssuesRouteRouteWithChildren
  WorkspaceSlugSettingsLabelsIndexRoute: typeof WorkspaceSlugSettingsLabelsIndexRoute
  WorkspaceSlugSettingsMembersIndexRoute: typeof WorkspaceSlugSettingsMembersIndexRoute
  WorkspaceSlugSettingsRolesIndexRoute: typeof WorkspaceSlugSettingsRolesIndexRoute
  WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute: typeof WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute
}

const WorkspaceSlugRouteRouteChildren: WorkspaceSlugRouteRouteChildren = {
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugTeamsIndexRoute: WorkspaceSlugTeamsIndexRoute,
  WorkspaceSlugTeamsTeamSlugIssuesRouteRoute:
    WorkspaceSlugTeamsTeamSlugIssuesRouteRouteWithChildren,
  WorkspaceSlugSettingsLabelsIndexRoute: WorkspaceSlugSettingsLabelsIndexRoute,
  WorkspaceSlugSettingsMembersIndexRoute:
    WorkspaceSlugSettingsMembersIndexRoute,
  WorkspaceSlugSettingsRolesIndexRoute: WorkspaceSlugSettingsRolesIndexRoute,
  WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute:
    WorkspaceSlugTeamsTeamSlugIssueIssueIdRoute,
}

const WorkspaceSlugRouteRouteWithChildren =
  WorkspaceSlugRouteRoute._addFileChildren(WorkspaceSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  WorkspaceSlugRouteRoute: WorkspaceSlugRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  InviteTokenRoute: InviteTokenRoute,
  WorkspaceCreateRoute: WorkspaceCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
